### ISSUE TITLE
expired feed warning  on feeds with valid calendar ranges

### ISSUE THREAD

**Issue by kpwebb** [conveyal/gtfs-validator#15]
It appears that feeds with valid calendar.txt ranges but no future valid calendar_dates.txt data are marked as expired. I assume this is because  the calendar_dates range trumps calendar.txt.

**Comment by mattwigway** [comment]
Worse than that, I'm afraid; calendars are not being considered at all (!)

**Comment by mattwigway** [comment]
No, I take that back.
